<%@ Page Language="C#" AutoEventWireup="true" Title="Field Permissions" MasterPageFile="~/Meta/MetaMain.Master" CodeBehind="FieldPermission_Add.aspx.cs" Inherits="SensysErp.Meta.FieldPermission_Add" ValidateRequest="false" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

    <%# HelperLib.Web.WebResources.GetResource("~/css/layout_grid.css")%>
    <%# HelperLib.Web.WebResources.GetResource("~/Scripts/knockout-2.2.1.js")%>

    <script type="text/javascript">
        var DashboardID = "";
        var AddMode = false;

        var dbCols = [];
        var dispname = "";
        var entitypath = "";
        var reservedKeywords = ["recordid", "entityname", "_preview"];

    </script>


    <style>
        #tvCtrEnt
        {
            position: absolute;
            display: none;
            width: 298px;
            height: 295px;
            border: solid 1px #DBD7D7;
            z-index: 10;
            box-shadow: 2px 2px 5px #555;
            overflow-y: auto;
            margin-top: -5px;
            background-color: #FFFFF5;
        }

        #tvCtrFld
        {   
            position: absolute;
            display: none;
            width: 298px;
            height: 295px;
            border: solid 1px #DBD7D7;
            z-index: 10;
            box-shadow: 2px 2px 5px #555;
            overflow-y: auto;
            margin-top: -5px;
            background-color: #FFFFF5;
        }

        #txtEntity
        {
            width: 288px;
            padding: 5px;
            font-size: 14px;
            color: #983434;
            margin-bottom: 5px;
            cursor: pointer;
            border: solid 1px #808080;
        }

        #rtvList
        {
            border: solid 1px #808080;
        }

        .divAutoGenerated
        {
            display: none;
            position: absolute;
            border: 1px solid #8B8B8B;
            width: 700px;
            top: 25px !important;
            padding: 20px;
        }

        .reToolbar
        {
            display: none;
        }

        .reModule
        {
            display: none;
        }

        .divTreeButton
        {
            height: 24px;
            width: 24px;
            font-family: fontawesome;
            font-size: 18px;
            font-weight: normal;
            position: absolute;
            margin-top: 0px;
            display: inline-block;
            vertical-align: top;
            padding-left: 2px;
        }

        .divAdvTreeSimple
        {
            height: 24px;
            width: 24px;
            font-family: fontawesome;
            font-size: 18px;
            font-weight: normal;
            display: inline-block;
        }

        .divTree
        {
            display: none;
            position: absolute;
            border: 1px solid #A1A1A1;
            height: 250px;
            width: 250px;
            overflow: auto;
            overflow-x: hidden;
            background-color: #F0F0F0;
            z-index: 100;
            box-shadow: 1px 1px 5px #555;
        }

        .DarkTheme .divTree
        {
            background-color: #414141;
        }

        .RedTheme .divTree
        {
            background-color: #F0ECE8;
        }

        .GreenTheme .divTree
        {
            background-color: #DEF7CB;
        }

        .BlueGlossTheme .divTree
        {
            background-color: #97c9f8;
        }

        .OrangeTheme .divTree
        {
            background-color: #FFE9D5;
        }

        #divPopup
        {
            display: none;
            position: fixed;
            z-index: 3500;
            padding: 20px;
            height: 100px;
            width: 350px;
        }

        #divEditor
        {
            display: none;
            position: absolute;
            z-index: 3500;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #fff;
        }

        .tblSeries
        {
            max-height: 170px;
            overflow-y: auto;
            vertical-align: top;
        }

        #tbl .td-value
        {
            padding: 0 5px;
        }

        .divCriteriaCss
        {
            width: 300px;
            vertical-align: top;
        }

        .Office2007.reWrapper, .Office2007.RadEditor .reContentCell, .Office2007.reColorPicker, .Office2007.reInsertTable, .Office2007.reCustomLinks a:hover
        {
            border: 0;
        }

        .reContentCell iframe
        {
            height: 33px !important;
        }

        .table-form .RadEditor TD
        {
            padding: 0;
        }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <hlp:ActionMessage ID="ActionMessage1" runat="server" />


            <div class="div-form">
                <table id="tdvalue" class="table-form" style="width: 510px;">

                    <tr>
                        <td class="td-label">
                            <asp:Label ID="lblEntity" runat="server" Text="Entity"></asp:Label>
                        </td>
                        <td class="td-value">
                            <asp:TextBox ID="txtEntity" runat="server" ReadOnly="true"></asp:TextBox>
                            <div id="tvCtrEnt">
                                <telerik:RadTreeView ID="tvEntity" OnClientNodeClicked="selectEntity" runat="server">
                                </telerik:RadTreeView>
                            </div>
                            <asp:HiddenField ID="hdnEntityID" runat="server" />
                        </td>
                    </tr>

                    <tr>
                        <td class="td-label">
                            <asp:Label ID="lblFieldName" runat="server" Text="Field Name"></asp:Label>
                        </td>
                        <td class="td-value">
                            <asp:TextBox ID="txtFieldName" runat="server" ReadOnly="true"></asp:TextBox>
                            <div id="tvCtrFld">
                                <telerik:RadTreeView ID="rtvList" runat="server" OnClientNodeClicked="selectField" OnClientNodePopulating="tvItems_NodePopulate">
                                    <WebServiceSettings Path="FieldPermission_Add.aspx" Method="GetEntityFields"></WebServiceSettings>
                                </telerik:RadTreeView>
                            </div>
                            <asp:HiddenField ID="hdnFieldID" runat="server" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="td-label">
                       
                             <asp:Label ID="lblUserRole" runat="server" CssClass="mainHeading" Text="Select User-Roles for which selected field is restricted"></asp:Label><br />
                            <div style="margin-left:70px;font-weight:bold">
                                <span class="col1">Select</span>
                                <span class="col2">Role Code</span>
                                <span class="col3">Role Name</span>
                                <span class="col4">Can Add</span>
                                <span class="col5">Can Edit</span>
                            </div>
                            <telerik:RadListBox ID="rlbUserRole"  runat="server" Style="margin-left:70px" Height="200px"  Width="655px">
                                	<ItemTemplate>
                                        <span class="col1">
                                        <asp:CheckBox ID="chkRole" runat="server" Checked='<%# !HelperLib.Conversion.C.IsBlank(DataBinder.Eval(Container.DataItem, "FieldPermissions_Pid")) %>' />
                                        </span><span class="col2">
                                         <%# DataBinder.Eval(Container.DataItem, "userRoleName") %>
		                                 </span><span class="col3">
                                        <%# DataBinder.Eval(Container.DataItem, "userRoleCode") %>
                                        </span><span class="col4">
                                         <asp:CheckBox ID="chkAdd" runat="server" Checked='<%# HelperLib.Conversion.C.Bool(DataBinder.Eval(Container.DataItem, "canadd")) %>' />
                                        </span><span class="col5">
                                        <asp:CheckBox ID="chkEdit" runat="server" Checked='<%# HelperLib.Conversion.C.Bool(DataBinder.Eval(Container.DataItem, "canedit")) %>' />
                                        </span>
                                        <asp:Label runat="server" ID="lblRole" style="display:none" Text='<%# DataBinder.Eval(Container.DataItem, "UserRole_pid") %>'></asp:Label>
                                	</ItemTemplate>
                            </telerik:RadListBox>
                           <span style="margin-left:70px;margin-bottom:20px;display:inline-block">Note: Roles that are not selected have full access to the field</span>
                        </td>
                    </tr>

                </table>
            </div>



            <div>
                <asp:LinkButton ID="btnSubmit" CssClass="cmdBtn cmdSave" runat="server" Text="Submit" OnClick="btnSubmit_Click"></asp:LinkButton>
                <asp:LinkButton ID="btnClose" class="cmdBtn cmdClose" runat="server" Text="Cancel" OnClientClick="closeForm();"></asp:LinkButton>
            </div>

            

            
            <asp:Button ID="btnLoadEntities" runat="server" Style="display: none" OnClick="btnLoadEntities_Click" />
            
        </ContentTemplate>
    </asp:UpdatePanel>
    <style>
        .col1 {
            display:inline-block;
            width:45px;
            text-align:center;
                overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
        }
        .col2 {
            display:inline-block;
            width:125px;
                overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
        }
        .col3 {
            display:inline-block;
            width:295px;
                overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
        }
        .col4 {
            display:inline-block;
            width:80px;
            text-align:center;
                overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
        }
        .col5 {
            display:inline-block;
            width:80px;
            text-align:center;
                overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
        }


    </style>
    <script type="text/javascript">



    </script>

    <script type="text/javascript">

        var ajx = Sys.WebForms.PageRequestManager.getInstance();
        ajx.add_pageLoaded(function () {
            if (typeof MDI != "undefined") {
                //Add user code here
                //alert("load "+MDI.id );             
            }
        })

        ajx.add_endRequest(function () {
            if (typeof MDI != "undefined") {
                //Add user code here
                //alert("load "+MDI.id );   
                CloseWindow();
            }
        })
    </script>

    <script type="text/javascript">
        var entityId = "", entityName = "";

        function pageLoad() {
           
           
        }


        if ($("#tvCtrEnt").exists()) {
            $("#<%=txtEntity.ClientID %>").on("click", function (e) {
                     toggleEntityTree(e.target); e.stopPropagation();
                 })
                 $(document).on("click", function () { $("#tvCtrEnt").hide(); })
                 $("#tvCtrEnt").on("click", function (e) { e.stopPropagation(); });
             }

             function selectEntity(sender, args) {

                 var t = $("#<%=txtEntity.ClientID %>");
                 var n = args.get_node();

                 if (n.get_level() < 2 && n.get_value() != "None")
                     return;
                 if (n.get_value() == "None") {
                     t.val("");
                     t.removeAttr("entityid");
                 }
                 else {
                     t.val("");
                     t.val(n.get_text());
                     entityId = n.get_value();
                     entityName = n.get_text();
                     $("#<%=hdnEntityID.ClientID %>").val(n.get_value());
                  LoadEntityTree();
              }
              $("#tvCtrEnt").hide();
          }


          




         function selectField(sender, args) {

             var t = $("#<%=txtFieldName.ClientID %>");
             var n = args.get_node();

             if (n.get_level() < 1 && n.get_value() != "None")
                 return;
             if (n.get_value() == "None") {
                 t.val("");

             }
             else {
                 t.val("");
                 t.val(n.get_text());
                 $("#<%=hdnFieldID.ClientID %>").val(n.get_value());
             }
             $("#tvCtrFld").hide();
         }


         function LoadEntityTree() {
             var t = $("#<%=txtFieldName.ClientID %>");
              t.val('');
              var tree = $find("<%= rtvList.ClientID %>");
             tree.get_nodes().clear();
             tree.trackChanges();
             var node = new Telerik.Web.UI.RadTreeNode();

           
                 node.set_text(entityName);
                 node.set_value(entityId);
                 node.get_attributes().setAttribute("ParentTable", entityId);
             


             node.set_expandMode(3);


             tree.get_nodes().add(node);
             tree.commitChanges();
         }


         function toggleEntityTree(txt) {
             $(txt).next().show();
         }



         function tvItems_NodePopulate(sender, args) {
             var node = args.get_node();
             var context = args.get_context();

             context["EntityID"] = node.get_attributes().getAttribute("ParentTable");
         }

         if ($("#tvCtrFld").exists()) {
             $("#<%=txtFieldName.ClientID %>").on("click", function (e) {
                 toggleEntityTree(e.target); e.stopPropagation();
             })
             $(document).on("click", function () { $("#tvCtrFld").hide(); })
             $("#tvCtrFld").on("click", function (e) { e.stopPropagation(); });
         }






    </script>

    




</asp:Content>


